dist: trusty
sudo: required

language: java

jdk:
  - oraclejdk8

notifications:
  email: false

services:
  - redis-server

addons:
  postgresql: "9.5"
  apt:
    packages:
      - net-tools
      - libpcre3-dev
      - build-essential

services:
  - redis
  - docker

env:
  global:
    - CASSANDRA_BASE=2.2.12
    - CASSANDRA_LATEST=3.9
    - DOWNLOAD_CACHE=$HOME/download-cache
    - INSTALL_CACHE=$HOME/install-cache
    - BUSTED_ARGS="-o gtest -v --exclude-tags=flaky,ipv6"
    - PLUGIN_NAME=azure-functions
    - KONG_TEST_CUSTOM_PLUGINS=$PLUGIN_NAME
    - KONG_CUSTOM_PLUGINS=$PLUGIN_NAME

  matrix:
    - CASSANDRA=$CASSANDRA_BASE
    - CASSANDRA=$CASSANDRA_LATEST

before_install:
  - git clone https://$GITHUB_TOKEN:@github.com/Kong/kong-ci.git
  - git clone https://github.com/Kong/kong.git kong-ce
  - source kong-ce/.requirements && OPENRESTY=$RESTY_VERSION LUAROCKS=$RESTY_LUAROCKS_VERSION OPENSSL=$RESTY_OPENSSL_VERSION PCRE=$RESTY_PCRE_VERSION source kong-ci/setup_env.sh

install:
  - luarocks make
  - cd kong-ce
  - make dev
  - createuser --createdb kong
  - createdb -U kong kong_tests

script:
  - bin/busted $BUSTED_ARGS ../spec

cache:
  apt: true
  pip: true
  directories:
    - $DOWNLOAD_CACHE
    - $INSTALL_CACHE
    - $HOME/.ccm/repository
