dist: bionic

jobs:
  include:
  - name: Enterprise 1.3.0.x
    env: KONG_VERSION=1.3.0.x
  - name: Enterprise 1.5.0.x
    env: KONG_VERSION=1.5.0.x
  - name: Enterprise 2.4.1.x
    env: KONG_VERSION=2.4.1.x
  - name: Kong CE 2.4.x
    env: KONG_VERSION=2.4.x
  - name: Nightly EE-master
    env: KONG_VERSION=nightly-ee POSTGRES=latest CASSANDRA=latest
  #- name: Nightly CE-master
  #  env: KONG_VERSION=nightly POSTGRES=latest CASSANDRA=latest

install:
- git clone --single-branch https://github.com/Kong/kong-pongo ../kong-pongo
- "../kong-pongo/pongo.sh up"
- "../kong-pongo/pongo.sh build"

script:
- "../kong-pongo/pongo.sh lint"
- "../kong-pongo/pongo.sh run"

notifications:
  slack:
    if: branch = master AND type != pull_request
    on_success: change
    on_failure: always
    rooms:
      secure: a7BP3Rz5SfllyvV1T18/kuqDwYsKSSmxh0swhiczxmMVV15vd4AJlnWrcwgTPT8WMQBfie4tXfJeJ9IXumfIwPu/xg/Rk/OBBczQOowUPVYPRyMAI7dcs0P+uqpyfJtVlrNVTO/+9kIn4O4JQh4ZSamseYMDTayh78oQY16x6hIR0ZieMGb/Sy87d0dqOpFFzm4GdrWRdKodILLSgNyVuy/68sM6l3pos8ioeO9W5jALhv2Uiw/9tva+5uJbgQp18kCZBfJFMOKbPSDXbHNDUtNr9jVl15Z1tvoxxEcJd/znIENRnvjxdSdXRcrJsHMTdFJxwqz4LfNrdbM5FVvjGLIHiWufpMqPFLOwY7Vrf0FuQk5mFx3q7zDsetLiTDw/XY/oaARnTj9gX+KFNQ7XWFCrSG/AobK751EaV1orXjtPT2jHIi0ii82/MNWhXUemCd+p8ZYunU4676Zpn2l3tWPguZUVzH1rY4yUnIWrAn1AVsloUVlZHW6FhcrLD2+DQ7ApLPO4pIyQismKTnz/DJTP1R1ec+mFKw4mQJTkq88sDk4cvAObXTS4NqXdKB8PusteHDpretRsY6btKoT+ctm5AgKSThhN7RRY1v5GuDRk+lIu0cq5w45kucwAJ0gAvQu5xaipKXyVA4nnQj7uCbFrBusYuha4gwLMfjTi91c=
